name: publish

on:
  pull_request:
    branches:
      - '*'

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up node and pnpm
        run: |
          corepack enable
          pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          pnpm i

      - name: publish
        run: pnpm publish --no-git-checks --access public